#!/usr/bin/env bash


lastdir="$(pwd)"
lastbranch="$(git branch --show-current)"
tag="$1"
branch="$2"

cd /tmp

git clone /home/acemany/projects/github/MindustryV4
cd MindustryV4
git checkout $branch

cp /home/acemany/projects/github/bekeystore.jks ../bekeystore.jks
cp /home/acemany/projects/github/MindustryV4/local.properties local.properties
cp /home/acemany/projects/github/MindustryV4/core/assets/version.properties core/assets/version.properties

./gradlew pack
./gradlew desktop:run -Pbuildversion=$tag -PversionType=bleeding-edge
./gradlew desktop:dist server:dist android:assembleRelease -Pbuildversion=$tag -PversionType=bleeding-edge --stacktrace

if [ -e ./android/build/outputs/apk/release/android-release.apk ] &&
   [ -e ./desktop/build/libs/desktop-release.jar ] &&
   [ -e ./server/build/libs/server-release.jar ]
then
  mv android/build/outputs/apk/release/android-release.apk android/build/outputs/apk/release/Mindustry-V4-BE-Android-$tag.apk
  mv desktop/build/libs/desktop-release.jar desktop/build/libs/Mindustry-V4-BE-Desktop-$tag.jar
  mv server/build/libs/server-release.jar server/build/libs/Mindustry-V4-BE-Server-$tag.jar

  gh release upload -R Acemany/MindustryV4Builds $tag android/build/outputs/apk/release/Mindustry-V4-BE-Android-$tag.apk desktop/build/libs/Mindustry-V4-BE-Desktop-$tag.jar server/build/libs/Mindustry-V4-BE-Server-$tag.jar
  echo Built SUCCESSFULLY tag $tag

else echo Built UNsuccessfully tag $tag
fi

rm -fr /tmp/MindustryV4

cd $lastdir
echo You are back in $lastdir
