name: Build Artifacts

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  RELEASE_VERSION: ${{ github.run_number }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    #- name: Set up keystore
    #  run: |
    #    echo "${{ secrets.KEYSTORE_BASE64 }}" > keystore.txt
    #    base64 --decode keystore.txt > bekeystore.jks

    - name: Create artifacts
      env:
        keystore_password: ${{ secrets.KEYSTORE_PASSWORD_SECRET }}
        keystore_alias_password: ${{ secrets.KEYSTORE_PASSWORD_SECRET }}
        keystore_alias: meow
      run: |
        git clone --depth=1 --branch=master https://github.com/acemany/MindustryV4_reforked
        cd MindustryV4_reforked
        echo "BODY=$RELEASE_VERSION" >> $GITHUB_ENV
        ./gradlew pack
        ./gradlew desktop:dist server:dist -Pbuildversion=${RELEASE_VERSION} -PversionType=bleeding-edge --stacktrace
        mv desktop/build/libs/desktop-release.jar desktop/build/libs/Mindustry-V4-BE-Desktop-${RELEASE_VERSION}.jar
        mv server/build/libs/server-release.jar server/build/libs/Mindustry-V4-BE-Server-${RELEASE_VERSION}.jar

    - name: Upload desktop artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        tag: ${{ RELEASE_VERSION }}
        body: ${{ env.BODY }}
        release_name: ${{ github.event.head_commit.message }}
        overwrite: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: MindustryV4_reforked/desktop/build/libs/Mindustry-V4-BE-Desktop-${{ env.RELEASE_VERSION }}.jar

    - name: Upload server artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        tag: ${{ RELEASE_VERSION }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: MindustryV4_reforked/server/build/libs/Mindustry-V4-BE-Server-${{ env.RELEASE_VERSION }}.jar
